services:
  tldw-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tldw-discord-bot
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_EXPIRATION_HOURS=${CACHE_EXPIRATION_HOURS:-24}
      - MESSAGE_HISTORY_LIMIT=${MESSAGE_HISTORY_LIMIT:-5}
    env_file:
      - .env
    networks:
      - tldw-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: tldw-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - tldw-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
    driver: local

networks:
  tldw-network:
    driver: bridge
