apiVersion: v1
kind: Service
metadata:
  name: tldw-bot-service
  namespace: tldw-bot
  labels:
    app: tldw-discord-bot
    component: bot
spec:
  type: ClusterIP
  selector:
    app: tldw-discord-bot
    component: bot
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health