apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tldw-bot
  labels:
    app: redis
    component: database
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: tldw-bot
  labels:
    app: redis
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis