# This is a template file. Replace the base64 encoded values with your actual secrets.
# To encode a secret: echo -n "your-secret-value" | base64
#
# Example usage:
# kubectl create secret generic tldw-secrets \
#   --from-literal=discord-token="your-discord-token" \
#   --from-literal=google-api-key="your-google-api-key" \
#   --from-literal=redis-password="your-redis-password" \
#   --namespace=tldw-bot

apiVersion: v1
kind: Secret
metadata:
  name: tldw-secrets
  namespace: tldw-bot
  labels:
    app: tldw-discord-bot
type: Opaque
data:
  # Replace these with your base64 encoded values
  # Use: echo -n "your-value" | base64
  discord-token: "REPLACE_WITH_BASE64_ENCODED_DISCORD_TOKEN"
  google-api-key: "REPLACE_WITH_BASE64_ENCODED_GOOGLE_API_KEY"
  redis-password: "REPLACE_WITH_BASE64_ENCODED_REDIS_PASSWORD"